### ISSUE TITLE
Parameter 'redirect_url' Typo

### ISSUE THREAD

**Issue by tajulsharby** [neonexxa/ecommerce#2]
Typo at file BillplzBill.php at line 41: `$this->data['redicrect_url']` should be `$this->data['redirect_url']` instead.

**Comment by neonexxa** [comment]
thanks for pointing that out. i fixed it in the latest push https://github.com/neonexxa/billplz-wrapper/commit/9f9b5c40fefae5522a3e4338eb1760c2cb9d43c5
